[package]
name = "configure-holochain"
version = "0.1.0"
authors = ["Oleksii Filonenko <oleksii.filonenko@holo.host>"]
edition = "2018"

[dependencies]
again = "0.1"
anyhow = "1.0"
futures = "0.3"
isahc = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
structopt = "0.3"
tempfile = "3.1"
# holochain_websocket uses tokio 0.2
# TODO: bump to 0.3 after https://github.com/holochain/holochain/pull/461 is merged
tokio = { version = "0.2", features = ["full"] }
tracing = { version = "0.1", features = ["attributes"] }
tracing-futures = "0.2"
tracing-subscriber = "0.2"
url = "2.2"
hc_utils = {git = "https://github.com/holochain/hc-utils", branch = "develop", package = "hc_utils"}

[dependencies.holochain]
git = "https://github.com/holochain/holochain"
rev = "ea026def01d1573d5e0edfb7f4e3e9453f88c43e"
package = "holochain"
default-features = false

[dependencies.holochain_types]
git = "https://github.com/holochain/holochain"
rev = "ea026def01d1573d5e0edfb7f4e3e9453f88c43e"
package = "holochain_types"

[dependencies.holochain_zome_types]
git = "https://github.com/holochain/holochain"
rev = "ea026def01d1573d5e0edfb7f4e3e9453f88c43e"
package = "holochain_zome_types"

[dependencies.holochain_websocket]
git = "https://github.com/holochain/holochain"
rev = "ea026def01d1573d5e0edfb7f4e3e9453f88c43e"
package = "holochain_websocket"

# Holochain requires a patch to crates.io registry

[patch.crates-io]
rkv = { git = "https://github.com/holochain/rkv.git", branch = "master" }
lmdb-rkv = { git = "https://github.com/holochain/lmdb-rs.git" }
