[package]
name = "self-hosted-happs"
version = "0.1.0"
authors = ["Oleksii Filonenko <oleksii.filonenko@holo.host>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
futures = "0.3.8"
isahc = "0.9.12"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.13"
structopt = "0.3.20"
tempfile = "3.1.0"
# holochain_websocket uses tokio 0.2
# TODO: add tokio v3->v2 compat layer https://github.com/LucioFranco/tokio-compat-02/
tokio = { version = "0.2", features = ["full"] }
tracing = { version = "0.1", features = ["attributes"] }
tracing-futures = "0.2"
tracing-subscriber = "0.2"
url = "2.2"
zip = "0.5.8"

[dependencies.holochain]
git = "https://github.com/holochain/holochain"
branch = "develop"
package = "holochain"

[dependencies.holochain_types]
git = "https://github.com/holochain/holochain"
branch = "develop"
package = "holochain_types"

[dependencies.holochain_websocket]
git = "https://github.com/holochain/holochain"
branch = "develop"
package = "holochain_websocket"

# Holochain requires a patch to crates.io registry

[patch.crates-io]
rkv = { git = "https://github.com/holochain/rkv.git", branch = "master" }
lmdb-rkv = { git = "https://github.com/holochain/lmdb-rs.git" }
